title: "Hydrométrie"
description : "Spécification du schéma de données du Sandre pour l'hydrométrie"
homepage: "https://github.com/Pierlou/test-schema-hydrometrie"

schemas:
  -
    path: "sandre-hydrometrie.json"
    title: "Hydrométrie"